services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    shm_size: 128mb
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: knm_senha
      POSTGRES_USER: knm_admin
      POSTGRES_DB: knm
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U knm_admin -d knm"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres_data: