services:
  web:
    build: .
    command: sh -c "npx prisma generate && npx next dev"
    ports:
      - "3000:3000"
    env_file:
      - .env.prod
    volumes:
      - ./:/opt/knm
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5430:5432"
    environment:
      POSTGRES_PASSWORD: knm_senha
      POSTGRES_USER: knm_admin
      POSTGRES_DB: knm
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persiste os dados do PostgreSQL
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U knm_admin -d knm" ]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  postgres_data: