services:
  web:
    build:
      context: ../
      dockerfile: ./dev/Dockerfile

    command: sh -c "npx prisma generate && npx prisma migrate deploy && npx next dev"
    ports:
      - "192.168.1.14:3000:3000"
    volumes:
      - ../:/opt/knm/
      - ../node_modules:/opt/knm/node_modules
      - ../.next/:/opt/knm/.next
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - "5431:5432"
    environment:
      POSTGRES_PASSWORD: knm_senha
      POSTGRES_USER: knm_admin
      POSTGRES_DB: knm
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Persiste os dados do PostgreSQL
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U knm_admin -d knm" ]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  postgres_data: