import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import MenuLateral from "@/components/menu/lateral";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "KNM Estudos e Pesquisas - Inspeção de gás com Segurança!",
    description: "Generated by create next app",
    authors: {
        url: "https://www.knm.srv.br/",
        name: "KNM Estudos e Pesquisa",
    },
    icons: {
        icon: "https://www.knm.srv.br/wp-content/uploads/2025/02/cropped-LOGO-PERFIL-IG-REDONDO-32x32.png",
        // Opcional: Adicione outros tamanhos se necessário
        shortcut: "https://www.knm.srv.br/wp-content/uploads/2025/02/cropped-LOGO-PERFIL-IG-REDONDO-32x32.png",
        apple: "https://www.knm.srv.br/wp-content/uploads/2025/02/cropped-LOGO-PERFIL-IG-REDONDO-180x180.png",
    }
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="pt-br" data-kantu="1">
        <body className="font-sans bg-amber-50">
        <div className="grid grid-cols-1 gap-2 md:grid-flow-col md:grid-cols-12">
            <MenuLateral className="hidden md:block md:col-span-2"/>
            <section className="col-span-12 md:col-span-10">{children}</section>
        </div>
        </body>
        </html>
    );
}
